variable "region" {}
variable "profile" {}
variable "vpc_id" {}
variable "sg_desc" {}
variable "subnet_id_1" {}
variable "subnet_id_2" {}
variable "private_ips_1" {}
variable "private_ips_2" {}
variable "ami_id" {}
variable "avb_zone_1" {}
variable "avb_zone_2" {}
variable "instance_type" {}
variable "key_name" {}
variable "ec2_name_1" {}
variable "ec2_name_2" {}
variable "reg" {}
variable "city" {}
variable "env" {}