variable "region" {}
variable "profile" {}
variable "app_name" {}
variable "reg" {}
variable "city" {}
variable "env" {}
variable "sg_desc" {}
variable "vpc_id" {}
variable "cidr_blocks" {}
variable "pgfamily" {}
variable "subnetdescription" {}
variable "subnet_ids" {}
variable "allocated_storage" {}
variable "engine_version" {}
variable "instance_class" {}
variable "db_name" {}
variable "db_user" {}
variable "db_password" {}
variable "option_group_description" {}
variable "engine_name" {}
variable "option_engine_version" {}
variable "cpu" {}
variable "memory" {}
variable "task_role_arn" {}
variable "container_name" {}
variable "container_image" {}
variable "alb_subnet_ids" {}
variable "alb_sg_desc" {}
variable "ecs_sg_desc" {}
variable "ecs_subnet_ids" {}