variable "region" {}
variable "profile" {}
variable "vpc_id" {}
variable "sg_desc" {}
variable "subnet_id" {}
variable "private_ips" {}
variable "ami_id" {}
variable "avb_zone" {}
variable "instance_type" {}
variable "key_name" {}
variable "ec2_name" {}
variable "reg" {}
variable "city" {}
variable "env" {}