variable "app_name" {}
variable "env" {}
variable "sg_name" {}
variable "sg_desc" {}
variable "vpc_id" {}
variable "cidr_blocks" {}
variable "pg_grp" {}
variable "pgfamily" {}
variable "snt_grp" {}
variable "subnetdescription" {}
variable "subnet_ids" {}
variable "rds_name" {}
variable "allocated_storage" {}
variable "engine" {}
variable "engine_version" {}
variable "instance_class" {}
variable "db_name" {}
variable "db_user" {}
variable "db_password" {}
variable "option_grp" {}
variable "option_group_description" {}
variable "engine_name" {}
variable "option_engine_version" {}