variable "vpc_id" {}
variable "sg_name" {}
variable "sg_desc" {}
variable "subnet_id" {}
variable "private_ips" {}
variable "eni_name" {}
variable "ami_id" {}
variable "avb_zone" {}
variable "instance_type" {}
variable "key_name" {}
variable "ec2_name" {}
variable "env" {}